### ISSUE TITLE
openTTY fails under windows

### ISSUE THREAD

**Issue by phish108** [indutny/reopen-tty#3]
Hi I run nodejs 9.3.0 under windows. The code crashes with the following error on line 13: 

```
TypeError: Cannot read property 'O_RDWR' of undefined
```

I tried to include the constants separately without success, because in this case an internal assertion of the FS code is thrown.

**Comment by ruyadorno** [comment]
@indutny tested it on windows and can confirm the issue 😞 

I guess the c++ bindings are missing the constants from the core api
